version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: university
      MONGO_USERNAME: admin
      MONGO_PASSWORD: secret
    restart: always
    volumes:
      - ./data/db:/data/db
      - ./data/scripts/mongo_init.sh:/docker-entrypoint-initdb.d/mongo_init.sh:ro
    networks:
      - internal
  app:
    container_name: university-app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - '3000:3000'
      - '30000:9229'
    environment:
      MONGO_DATABASE: university
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USERNAME: admin
      MONGO_PASSWORD: secret
    networks:
      - internal
    depends_on:
      - mongodb
    restart: always
  api:
    container_name: university-api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/:/api/
      - /api/node_modules
    networks:
      - internal
    depends_on:
      - app
    ports:
      - '80:3001'
      - '40000:9229'
    restart: always

networks:
  internal: